# Generated by Django 3.2.9 on 2021-11-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='título')),
                ('link', models.URLField(blank=True, null=True)),
                ('view', models.IntegerField(blank=True, default=0, null=True, verbose_name='visualização')),
            ],
            options={
                'verbose_name': 'vídeo',
                'verbose_name_plural': 'vídeos',
                'ordering': ('id',),
            },
        ),
    ]
